export const resume = {
  en: {
    name: 'Sergey Volynkin',
    headline: 'Software & Platform Engineer',
    location: 'Saint Petersburg',
    availability: 'Open to office roles in Saint Petersburg, hybrid, remote and contract work with Russian or international companies. International relocation with employer support.',
    summary: 'I work across software development and infrastructure: adapt open-source products, build services and operate them on Linux. My work combines Python development, changes to existing Go codebases, Docker deployment, databases, CI/CD, monitoring and identity integrations. I take changes from source code through integration to production support.',
    metaDescription: 'Sergey Volynkin — Software & Platform Engineer. Open-source customization, Python, Go codebases, Linux, Docker, CI/CD and production operations. Saint Petersburg; open to remote work.',
    ui: { skip: 'Skip to content', navLabel: 'Resume sections', languageLabel: 'Resume language', print: 'Print / Save PDF', backToTop: 'Back to top', email: 'Email', phone: 'Phone', github: 'GitHub', telegram: 'Telegram', experience: 'Current experience', projects: 'Selected projects', otherProjects: 'Other engineering projects', skills: 'Technical skills', background: 'Earlier management experience', education: 'Education', contacts: 'Get in touch', projectLink: 'Visit project', moreProjects: 'Earlier software projects' },
    contacts: [
      { label: 'Email', value: 'volynkin.s04@gmail.com', href: 'mailto:volynkin.s04@gmail.com' },
      { label: 'Telegram', value: '@volynkin_s', href: 'https://t.me/volynkin_s' },
      { label: 'GitHub', value: 'github.com/volynkinss', href: 'https://github.com/volynkinss' },
      { label: 'Phone', value: '+7 (999) 022-60-61', href: 'tel:+79990226061' },
    ],
    employment: {
      company: 'IBK LLC', role: 'Lead System Administrator', department: 'Import Substitution Solutions Department', period: 'Sep 2025 — Present',
      overview: 'Implement and adapt open-source solutions in a six-person engineering team. My scope covers source code changes, Linux operations, deployment, application integrations and troubleshooting.',
      cases: [
        { id: 'rdpgw', title: 'RDPGW', subtitle: 'Business-critical remote access', status: 'Production · 70–100 daily users',
          bullets: ['Added terminal farm / RDS collection support to an existing Go gateway, plus SQLite-backed connection history, active-session views and filtered Excel export.', 'Build, deploy and support the gateway used for remote work; investigate authentication and connection issues.'],
          stack: ['Go', 'Linux', 'Docker', 'SQLite', 'OIDC'] },
        { id: 'dashboard', title: 'Dashboard', subtitle: 'Internal service catalog',
          bullets: ['Built a FastAPI portal with a PostgreSQL service catalog, Dashy YAML import and a bilingual interface.', 'Integrated Keycloak/OIDC sign-in, group-based service visibility, persistent sessions and audit logging; packaged the portal with Docker Compose.'],
          stack: ['Python', 'FastAPI', 'Jinja2', 'PostgreSQL', 'Keycloak', 'Docker Compose'], links: [{ label: 'Source on GitHub', url: 'https://github.com/volynkinss/dashboard' }] },
        { id: 'pulp', title: 'Pulp', subtitle: 'Package and artifact repositories', status: 'In progress',
          bullets: ['Evaluate and deploy Pulp in Docker: repositories, remotes, distributions, reverse proxy and authentication integration.', 'Design the operating model for upstream retrieval and local artifact reuse, including serving previously downloaded artifacts without external internet access.'],
          stack: ['Pulp', 'Docker', 'Reverse proxy'] },
        { id: 'keycloak', title: 'Keycloak', subtitle: 'Application identity integration',
          bullets: ['Administer Keycloak and integrate applications with SAML 2.0 and OIDC together with my manager.', 'Troubleshoot SAMLResponse assertions, NameID and attribute mapping, ACS flows and service provider / identity provider interactions.'],
          stack: ['Keycloak', 'SAML 2.0', 'OIDC'] },
      ],
      automation: 'Automated export of Postman API collections and environments for migration to Hoppscotch.',
    },
    projectIntro: 'Independent engineering and product work alongside my current employment. Software development, deployment and ongoing service operations.',
    projects: [
      { id: 'boltfather', title: 'BoltFather', role: 'Co-owner & Backend / Platform Engineer · 25% ownership', period: 'Feb 2024 — Present', status: 'Production',
        description: 'Telegram community access and subscription service with TON integrations.',
        bullets: ['Rebuilt the project from scratch and continue to own backend development, the bot layer, infrastructure, deployment and operations.', 'Automated delivery with GitHub Actions, GHCR images, SSH deployment, Alembic migrations and Docker Compose.', 'Deployed Prometheus, Grafana and Loki/Promtail for application metrics and Docker logs; added operational reporting backed by PostgreSQL.'],
        stack: ['Python', 'FastAPI', 'aiogram', 'PostgreSQL', 'Redis', 'Docker Compose', 'GitHub Actions', 'Prometheus', 'Grafana', 'Loki'],
        links: [{ label: 'BoltFather website', url: 'https://boltfather.com/' }] },
      { id: 'kvartirka', title: 'Kvartirka', role: 'Software development & deployment', status: 'In development',
        description: 'A workspace for managing rental properties, bookings and financial records.',
        bullets: ['Develop a NestJS/Fastify API and Next.js interface with Prisma/PostgreSQL and Redis: properties, bookings, payments, expenses and documents.', 'Build portfolio financial workflows and automate Docker Compose deployment, health checks and smoke validation through GitHub Actions.'], stack: ['TypeScript', 'NestJS', 'Next.js · React', 'Prisma', 'PostgreSQL', 'Redis', 'Docker Compose', 'GitHub Actions'],
        links: [{ label: 'Project website', url: 'https://rentalkeeper.ru/' }] },
      { id: 'supplier-parser', title: 'Supplier Price Parser', role: 'Software development & deployment',
        description: 'A service for collecting supplier price lists and preparing structured data for review and ordering.',
        bullets: ['Build Telegram/XLSX ingestion, a protected operator workspace, catalog matching and order preparation in FastAPI.', 'Preserve source snapshots and audit history in PostgreSQL; implement background jobs and advisory LLM candidate ranking with explicit operator confirmation.'], stack: ['Python', 'FastAPI', 'PostgreSQL', 'Telegram', 'OpenPyXL', 'OpenRouter', 'Docker Compose', 'GitHub Actions'] },
      { id: 'deliveries', title: 'Deliveries', role: 'Software development & deployment', period: 'Jan 2025 — Present',
        description: 'Delivery planning with geographic zones, address processing and route calculation.',
        bullets: ['Build a FastAPI/PostGIS backend and React map interface for address imports, geocoding, courier workflows and access control.', 'Integrate OSRM routing, H3 zone recommendations for review and LLM fallback parsing of unstructured delivery text; maintain Docker and CI/CD workflows.'], stack: ['Python', 'FastAPI', 'PostgreSQL · PostGIS', 'React · TypeScript', 'OSRM', 'H3', 'Docker', 'GitHub Actions'] },
    ],
    otherProjects: [
      { id: 'user-balances', title: 'User Balances', period: 'Feb 2025 — Jul 2025', description: 'Backend development for TON data processing: service APIs, block parsing, queue workers and database models.', stack: ['FastAPI', 'PostgreSQL', 'Redis', 'RabbitMQ', 'Taskiq'] },
      { id: 'scale-api', title: 'Scale API', period: 'Mar 2025', status: 'Project closed', description: 'Developed an API and background synchronization for staking and on-chain data.', stack: ['FastAPI', 'PostgreSQL', 'Alembic', 'Docker'] },
      { id: 'printly3d', title: 'Printly3D', period: 'Aug 2025 — Nov 2025', status: 'Project closed', description: 'Developed a Telegram bot and backend for 3D-printing order workflows.', stack: ['Python', 'aiogram', 'PostgreSQL', 'Alembic', 'Docker'] },
      { id: 'token-prices', title: 'Token Prices', description: 'Built token price monitoring and Telegram notifications with TON integrations, Redis state and automated Docker deployment.', stack: ['aiogram', 'Redis', 'TON APIs', 'Docker'] },
      { id: 'fanton-rent', title: 'Fanton Rent', period: 'Apr 2025 — Oct 2025', status: 'Project closed', description: 'Developed a bot for in-game asset rentals, integrating the Fanton API with wallet and reservation workflows.', stack: ['Python', 'aiogram', 'Redis', 'TON APIs', 'GitHub Actions'] },
    ],
    skills: [
      { title: 'Core practice', description: 'Service development and production operations.', items: ['Linux', 'Python · FastAPI · async I/O', 'Docker · Docker Compose', 'PostgreSQL · SQLAlchemy · Alembic', 'Nginx · reverse proxy', 'REST APIs · service integrations'] },
      { title: 'Hands-on engineering', description: 'Implemented in applications and deployment workflows.', items: ['Go — existing codebase modification', 'SQLite · Redis', 'TypeScript · NestJS · React/Next.js', 'CI/CD · GitHub Actions', 'Prometheus · Grafana · Loki', 'Keycloak · SAML 2.0 · OIDC'] },
      { title: 'Project-specific tools', items: ['Pulp — implementation in progress', 'PostGIS · OSRM', 'RabbitMQ · Taskiq', 'aiogram · TON integrations', 'LLM API integrations'] },
      { title: 'Developing further', description: 'Basic exposure through individual deployment tasks; continuing to learn.', items: ['Kubernetes', 'Helm', 'werf'] },
    ],
    background: { company: 'M.Video-Eldorado', role: 'Sales Floor Manager', period: 'Aug 2016 — Sep 2022', description: 'Progressed from sales to management. Around three years managing teams of up to 20 people: organizing daily work, coordinating the team and taking responsibility for store-floor operations. Later transitioned into software engineering.' },
    education: { institution: 'Saint Petersburg State Institute of Technology (Technical University)', degree: 'Bachelor’s degree · Applied Informatics', year: '2017' },
    languages: 'Russian · English',
    footer: 'Sergey Volynkin · Saint Petersburg',
  },
  ru: {
    name: 'Сергей Волынкин',
    headline: 'Инженер по разработке ПО и инфраструктуре',
    location: 'Санкт-Петербург',
    availability: 'Рассматриваю офис в Санкт-Петербурге, гибрид, удалённую и контрактную работу в российских и международных компаниях. Международный релокейт — при поддержке работодателя.',
    summary: 'Работаю на пересечении разработки и инфраструктуры: дорабатываю open-source продукты, создаю сервисы и сопровождаю их на Linux. Совмещаю разработку на Python, изменения существующих кодовых баз на Go, развёртывание в Docker, работу с БД, CI/CD, мониторингом и аутентификацией. Довожу изменения от исходного кода до интеграции и сопровождения в эксплуатации.',
    metaDescription: 'Сергей Волынкин — инженер по разработке ПО и инфраструктуре. Доработка open-source продуктов, Python, Go, Linux, Docker, CI/CD и эксплуатация сервисов. Санкт-Петербург, удалённая работа.',
    ui: { skip: 'Перейти к содержимому', navLabel: 'Разделы резюме', languageLabel: 'Язык резюме', print: 'Печать / Сохранить PDF', backToTop: 'Вернуться к началу', email: 'Почта', phone: 'Телефон', github: 'GitHub', telegram: 'Telegram', experience: 'Текущая работа', projects: 'Основные проекты', otherProjects: 'Другие инженерные проекты', skills: 'Технические навыки', background: 'Управленческий опыт', education: 'Образование', contacts: 'Связаться со мной', projectLink: 'Перейти к проекту', moreProjects: 'Другие программные проекты' },
    contacts: [
      { label: 'Почта', value: 'volynkin.s04@gmail.com', href: 'mailto:volynkin.s04@gmail.com' },
      { label: 'Telegram', value: '@volynkin_s', href: 'https://t.me/volynkin_s' },
      { label: 'GitHub', value: 'github.com/volynkinss', href: 'https://github.com/volynkinss' },
      { label: 'Телефон', value: '+7 (999) 022-60-61', href: 'tel:+79990226061' },
    ],
    employment: {
      company: 'ООО «Ай Би Кей»', role: 'Главный системный администратор', department: 'Отдел импортозамещающих решений', period: 'сен. 2025 — настоящее время',
      overview: 'Внедряю и дорабатываю open-source решения в составе инженерной команды из шести человек. Занимаюсь изменением кода, эксплуатацией Linux, развёртыванием, интеграцией приложений и диагностикой проблем.',
      cases: [
        { id: 'rdpgw', title: 'RDPGW', subtitle: 'Критически важный сервис удалённого доступа', status: 'В эксплуатации · 70–100 пользователей ежедневно',
          bullets: ['Добавил в существующий шлюз на Go поддержку терминальных ферм и коллекций RDS, историю подключений в SQLite, просмотр активных сеансов и выгрузку в Excel с фильтрами.', 'Собираю, развёртываю и сопровождаю шлюз для удалённой работы; диагностирую проблемы аутентификации и подключения.'],
          stack: ['Go', 'Linux', 'Docker', 'SQLite', 'OIDC'] },
        { id: 'dashboard', title: 'Dashboard', subtitle: 'Каталог внутренних сервисов',
          bullets: ['Разработал портал на FastAPI с каталогом сервисов в PostgreSQL, импортом из Dashy YAML и двуязычным интерфейсом.', 'Интегрировал вход через Keycloak/OIDC, доступ к сервисам по группам, хранение сессий и журнал действий; подготовил развёртывание в Docker Compose.'], stack: ['Python', 'FastAPI', 'Jinja2', 'PostgreSQL', 'Keycloak', 'Docker Compose'],
          links: [{ label: 'Код на GitHub', url: 'https://github.com/volynkinss/dashboard' }] },
        { id: 'pulp', title: 'Pulp', subtitle: 'Репозитории пакетов и артефактов', status: 'В процессе внедрения',
          bullets: ['Исследую и внедряю Pulp в Docker: репозитории, удалённые источники, публикации, обратное проксирование и интеграция аутентификации.', 'Прорабатываю получение артефактов из upstream и повторную выдачу локальных копий, включая доступ к ранее загруженным артефактам без внешнего интернета.'],
          stack: ['Pulp', 'Docker', 'Обратное проксирование'] },
        { id: 'keycloak', title: 'Keycloak', subtitle: 'Интеграция аутентификации приложений',
          bullets: ['Совместно с руководителем администрирую Keycloak и интегрирую приложения по SAML 2.0 и OIDC.', 'Разбираю SAMLResponse и assertions, сопоставление NameID и атрибутов, обработку ACS и взаимодействие приложения с провайдером идентификации.'],
          stack: ['Keycloak', 'SAML 2.0', 'OIDC'] },
      ],
      automation: 'Автоматизировал экспорт коллекций API и окружений Postman для переноса в Hoppscotch.',
    },
    projectIntro: 'Собственная разработка и работа над продуктами параллельно с текущей занятостью: приложения, развёртывание и сопровождение сервисов.',
    projects: [
      { id: 'boltfather', title: 'BoltFather', role: 'Совладелец и инженер по бэкенду и инфраструктуре · доля 25%', period: 'фев. 2024 — настоящее время', status: 'В эксплуатации',
        description: 'Сервис управления доступом и подписками в Telegram-сообществах с интеграциями TON.',
        bullets: ['Переписал проект с нуля; продолжаю развивать бэкенд, бота, инфраструктуру, развёртывание и эксплуатацию.', 'Автоматизировал доставку через GitHub Actions: образы в GHCR, развёртывание по SSH, миграции Alembic и Docker Compose.', 'Самостоятельно развернул Prometheus, Grafana и Loki/Promtail для метрик приложения и логов Docker; добавил операционные отчёты по данным PostgreSQL.'],
        stack: ['Python', 'FastAPI', 'aiogram', 'PostgreSQL', 'Redis', 'Docker Compose', 'GitHub Actions', 'Prometheus', 'Grafana', 'Loki'],
        links: [{ label: 'Сайт BoltFather', url: 'https://boltfather.com/' }] },
      { id: 'kvartirka', title: 'Kvartirka', role: 'Разработка и развёртывание', status: 'В разработке',
        description: 'Рабочее пространство для управления арендными объектами, бронированиями и финансовым учётом.',
        bullets: ['Разрабатываю API на NestJS/Fastify и интерфейс на Next.js с Prisma/PostgreSQL и Redis: объекты, бронирования, платежи, расходы и документы.', 'Развиваю финансовый учёт по портфелю и объектам; автоматизирую развёртывание Docker Compose и проверки доступности через GitHub Actions.'], stack: ['TypeScript', 'NestJS', 'Next.js · React', 'Prisma', 'PostgreSQL', 'Redis', 'Docker Compose', 'GitHub Actions'],
        links: [{ label: 'Сайт проекта', url: 'https://rentalkeeper.ru/' }] },
      { id: 'supplier-parser', title: 'Парсер прайсов поставщиков', role: 'Разработка и развёртывание',
        description: 'Сервис сбора прайсов поставщиков и подготовки структурированных данных для проверки и формирования заказов.',
        bullets: ['Создаю на FastAPI обработку Telegram/XLSX, защищённый кабинет оператора, сопоставление каталога и подготовку заказов.', 'Сохраняю исходные снимки и журнал действий в PostgreSQL; реализую фоновые задания и рекомендации LLM с обязательным подтверждением оператора.'], stack: ['Python', 'FastAPI', 'PostgreSQL', 'Telegram', 'OpenPyXL', 'OpenRouter', 'Docker Compose', 'GitHub Actions'] },
      { id: 'deliveries', title: 'Deliveries', role: 'Разработка и развёртывание', period: 'янв. 2025 — настоящее время',
        description: 'Планирование доставок: географические зоны, обработка адресов и расчёт маршрутов.',
        bullets: ['Разрабатываю бэкенд FastAPI/PostGIS и карту на React: импорт адресов, геокодирование, работу курьеров и разграничение доступа.', 'Интегрирую маршрутизацию OSRM, рекомендации зон H3 с проверкой оператором и резервный LLM-разбор неструктурированного текста; поддерживаю Docker и CI/CD.'], stack: ['Python', 'FastAPI', 'PostgreSQL · PostGIS', 'React · TypeScript', 'OSRM', 'H3', 'Docker', 'GitHub Actions'] },
    ],
    otherProjects: [
      { id: 'user-balances', title: 'User Balances', period: 'фев. 2025 — июл. 2025', description: 'Разработка бэкенда для обработки данных TON: API, парсинг блоков, очереди задач, воркеры и модели БД.', stack: ['FastAPI', 'PostgreSQL', 'Redis', 'RabbitMQ', 'Taskiq'] },
      { id: 'scale-api', title: 'Scale API', period: 'мар. 2025', status: 'Проект закрыт', description: 'Разработал API и фоновую синхронизацию данных стейкинга и блокчейна.', stack: ['FastAPI', 'PostgreSQL', 'Alembic', 'Docker'] },
      { id: 'printly3d', title: 'Printly3D', period: 'авг. 2025 — нояб. 2025', status: 'Проект закрыт', description: 'Разработал Telegram-бота и бэкенд для обработки заказов на 3D-печать.', stack: ['Python', 'aiogram', 'PostgreSQL', 'Alembic', 'Docker'] },
      { id: 'token-prices', title: 'Token Prices', description: 'Разработал мониторинг цен токенов и уведомления в Telegram: интеграции TON, хранение состояния в Redis и автоматизированное развёртывание Docker.', stack: ['aiogram', 'Redis', 'TON APIs', 'Docker'] },
      { id: 'fanton-rent', title: 'Fanton Rent', period: 'апр. 2025 — окт. 2025', status: 'Проект закрыт', description: 'Разработал бота для аренды игровых активов: интеграция с Fanton API, кошельками и логикой бронирования.', stack: ['Python', 'aiogram', 'Redis', 'TON APIs', 'GitHub Actions'] },
    ],
    skills: [
      { title: 'Основная практика', description: 'Разработка сервисов и их эксплуатация.', items: ['Linux', 'Python · FastAPI · асинхронный ввод-вывод', 'Docker · Docker Compose', 'PostgreSQL · SQLAlchemy · Alembic', 'Nginx · обратное проксирование', 'REST API · интеграции сервисов'] },
      { title: 'Практический опыт', description: 'Реализация в приложениях и процессах развёртывания.', items: ['Go — доработка существующих кодовых баз', 'SQLite · Redis', 'TypeScript · NestJS · React/Next.js', 'CI/CD · GitHub Actions', 'Prometheus · Grafana · Loki', 'Keycloak · SAML 2.0 · OIDC'] },
      { title: 'В отдельных проектах', items: ['Pulp — внедрение в процессе', 'PostGIS · OSRM', 'RabbitMQ · Taskiq', 'aiogram · интеграции TON', 'Интеграции с LLM API'] },
      { title: 'Развиваю дальше', description: 'Начальный опыт в отдельных задачах развёртывания; продолжаю изучение.', items: ['Kubernetes', 'Helm', 'werf'] },
    ],
    background: { company: 'М.Видео-Эльдорадо', role: 'Менеджер торгового зала', period: 'авг. 2016 — сен. 2022', description: 'Прошёл путь от продавца до менеджера. Около трёх лет управлял командами до 20 человек: организовывал ежедневную работу, координировал сотрудников и отвечал за работу торгового зала. Позднее перешёл в разработку ПО.' },
    education: { institution: 'Санкт-Петербургский государственный технологический институт (технический университет)', degree: 'Бакалавр · Прикладная информатика', year: '2017' },
    languages: 'Русский · Английский',
    footer: 'Сергей Волынкин · Санкт-Петербург',
  },
};
